get http://localhost:3000/api/user HTTP/1.1

###

POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "userName": "ocph23.test",
    "password": "Sony@77"
}


###

POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
    "userName": "ocph23",
    "email":"ocph23@gmail.com",
    "password": "Sony@77",
    "roles":"admin"
}

####

POST https://asabrimonitoring.herokuapp.com/api/auth/register HTTP/1.1
content-type: application/json

{
     "userName": "ocph23",
    "email":"ocph23@gmail.com",
    "password": "Sony@77",
    "roles":"admin"
}
####

###
GET  http://localhost:3000/api/auth/me HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6Im1pdHJhIiwiaWF0IjoxNTY4NTM2ODUwLCJleHAiOjE1Njg2MjMyNTB9.S4tNSl0X7bYnzfKfCrZcN4vDqhCq1Dqhb2gZwGViFIw